name: Woofy
on: pull_request_target
jobs:
  greet:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:      
      - uses: HarishTeens/hacktoberfest-greet@v1.1.0
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}